<a href="https://colab.research.google.com/github/tanvibane/diabetespedigreefuncyion/blob/main/diabetespedigreefuncyion_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes (1).csv


In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('diabetes.csv')

In [ ]:
df.columns=df.columns.str.lower()

In [ ]:
df.head()

pregnancies  glucose  bloodpressure  skinthickness  insulin   bmi  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   diabetespedigreefunction  age  outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.shape

(768, 9)

In [ ]:
df.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age', 'outcome'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   pregnancies               768 non-null    int64  
 1   glucose                   768 non-null    int64  
 2   bloodpressure             768 non-null    int64  
 3   skinthickness             768 non-null    int64  
 4   insulin                   768 non-null    int64  
 5   bmi                       768 non-null    float64
 6   diabetespedigreefunction  768 non-null    float64
 7   age                       768 non-null    int64  
 8   outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.size

6912

In [ ]:
df.dtypes

pregnancies                   int64
glucose                       int64
bloodpressure                 int64
skinthickness                 int64
insulin                       int64
bmi                         float64
diabetespedigreefunction    float64
age                           int64
outcome                       int64
dtype: object

In [ ]:
df.describe()

pregnancies     glucose  bloodpressure  skinthickness     insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              bmi  diabetespedigreefunction         age     outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
df.isnull().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [ ]:
df.mean(numeric_only=True)

pregnancies                   3.845052
glucose                     120.894531
bloodpressure                69.105469
skinthickness                20.536458
insulin                      79.799479
bmi                          31.992578
diabetespedigreefunction      0.471876
age                          33.240885
outcome                       0.348958
dtype: float64

In [ ]:
df.count()

pregnancies                 768
glucose                     768
bloodpressure               768
skinthickness               768
insulin                     768
bmi                         768
diabetespedigreefunction    768
age                         768
outcome                     768
dtype: int64

In [ ]:
for col in df.columns:
    if col != 'outcome':
        zero_count = (df[col] == 0).sum()
        if zero_count > 0:
            print(f"Column '{col}' has {zero_count} zero values")

Column 'pregnancies' has 111 zero values
Column 'glucose' has 5 zero values
Column 'bloodpressure' has 35 zero values
Column 'skinthickness' has 227 zero values
Column 'insulin' has 374 zero values
Column 'bmi' has 11 zero values


In [ ]:
(df==0).any()

pregnancies                  True
glucose                      True
bloodpressure                True
skinthickness                True
insulin                      True
bmi                          True
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
# columns where 0 is not a valid medical value

invalid_zero_cols = [
    'glucose',
    'bloodpressure',
    'skinthickness',
    'insulin',
    'bmi'
]

# replace 0 with nan
df[invalid_zero_cols] = df[invalid_zero_cols].replace(0, np.nan)


In [ ]:
df.sum()

pregnancies                  2953.000
glucose                     92847.000
bloodpressure               53073.000
skinthickness               15772.000
insulin                     61286.000
bmi                         24570.300
diabetespedigreefunction      362.401
age                         25529.000
outcome                       268.000
dtype: float64

In [ ]:
df.isnull().sum()

pregnancies                   0
glucose                       5
bloodpressure                35
skinthickness               227
insulin                     374
bmi                          11
diabetespedigreefunction      0
age                           0
outcome                       0
dtype: int64

In [ ]:
#  import missing values
for col in invalid_zero_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipython-input-3921740143.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)


In [ ]:
df.isnull().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [ ]:
(df==0).any()

pregnancies                  True
glucose                     False
bloodpressure               False
skinthickness               False
insulin                     False
bmi                         False
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
# median represents :-> a typical patient not too high not too low not
#  influenced but outliers


In [ ]:
# feature target sepration
# feature
x=df.drop('outcome',axis=1)
# target
y=df['outcome']


In [ ]:
x.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age'],
      dtype='object')

In [ ]:
y.name

'outcome'

In [ ]:
# train and test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
print(y.value_counts(normalize=True))

outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64


In [ ]:
print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of x_test: {x_test.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of x_train: (614, 8)
Shape of y_train: (614,)
Shape of x_test: (154, 8)
Shape of y_test: (154,)


In [ ]:
y.value_counts()

outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
y_train.value_counts()

outcome
0    401
1    213
Name: count, dtype: int64

In [ ]:
y_test.value_counts()


outcome
0    99
1    55
Name: count, dtype: int64

In [ ]:
y.value_counts(normalize=True)

outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

In [ ]:
y_train.value_counts(normalize=True)

outcome
0    0.653094
1    0.346906
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize=True)

outcome
0    0.642857
1    0.357143
Name: proportion, dtype: float64

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)


In [ ]:
# here using logistic regression classifier because it is
#  a binary classification problem ,storng base line medecal data
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(x_train_scaled,y_train)

# here now the model trained ,uses scaled features,can implement safety

LogisticRegression()

In [ ]:
y_pred=log_reg.predict(x_test_scaled)

In [ ]:
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
# accurancy of test
log_reg.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
# accurancy of train
log_reg.score(x_train_scaled,y_train)

0.7719869706840391

In [ ]:
# linear regression probability prediction
y_prob=log_reg.predict_proba(x_test_scaled)

In [ ]:
 y_prob[:20]

array([[0.71728313, 0.28271687],
       [0.83606362, 0.16393638],
       [0.89460661, 0.10539339],
       [0.84634265, 0.15365735],
       [0.54099098, 0.45900902],
       [0.55368795, 0.44631205],
       [0.98575091, 0.01424909],
       [0.62421038, 0.37578962],
       [0.42665813, 0.57334187],
       [0.24360418, 0.75639582],
       [0.77865771, 0.22134229],
       [0.11129996, 0.88870004],
       [0.60647622, 0.39352378],
       [0.72132736, 0.27867264],
       [0.92391448, 0.07608552],
       [0.59547239, 0.40452761],
       [0.88852602, 0.11147398],
       [0.92581118, 0.07418882],
       [0.28696241, 0.71303759],
       [0.4276886 , 0.5723114 ]])

In [ ]:
y_prob_diabetic = y_prob[:, 1]
y_prob_diabetic[:10]

array([0.28271687, 0.16393638, 0.10539339, 0.15365735, 0.45900902,
       0.44631205, 0.01424909, 0.37578962, 0.57334187, 0.75639582])

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

# [TN FP]
# [FN TP]

# TN - true negative-actually non dibetic
# FP - false positive-actually non diabetic but predicted diabetic
# FN - false negative-actually diabetic but predicted non diabetic
# TP - true positive-actually diabetic


array([[82, 17],
       [21, 34]])

In [ ]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

# here we will see about precision,recall,f1-score and support

# precision: how correct the model was when  it said 0 or 1
# recall: how many real 0 and 1 it found
# fitbalance: score of precision and recall
# support: how many actual 0 and 1 patients

# example for weighted avg
# classes with more sample influence the final score more than
# the smaller classes


              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154



In [ ]:
# next model we using here is svm support vector
# mechine ,it finds a string ,margin based decision
# boundary that often improve recall on small,
# well scalled datasets

# the main reason to use is datasets is small in size,we did the scalling ,chances are
# high to get better recall


In [ ]:
from sklearn.svm import SVC
svm_model=SVC(kernel='linear',probability=True)
svm_model.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [ ]:
y_pred_svm=svm_model.predict(x_test_scaled)
# evaluating
svm_model.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
from sklearn.metrics import confusion_matrix
cm_svm=confusion_matrix(y_test,y_pred_svm)
cm_svm

array([[82, 17],
       [21, 34]])

In [ ]:
y_prob_svm=svm_model.predict_proba(x_test_scaled)
y_prob_svm_diabetic=y_prob_svm[:,1]

In [ ]:
y_prob_svm_diabetic[:10]

array([0.29123703, 0.18347648, 0.12194602, 0.1679    , 0.47629983,
       0.46072141, 0.02105307, 0.3617802 , 0.55783383, 0.74149803])

In [ ]:
y_pred_svm[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
y_test[:10]

668    0
324    0
624    0
690    0
473    0
204    0
97     0
336    0
568    0
148    0
Name: outcome, dtype: int64

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154



In [ ]:
# ROC AUC Reciver operating characteristic ,Area under the curve

from sklearn.metrics import roc_curve,roc_auc_score
roc_auc_lr=roc_auc_score(y_test,y_prob[:,1])
roc_auc_svm=roc_auc_score(y_test,y_prob_svm[:,1])
roc_auc_lr,roc_auc_svm

# 81 for both lr and sum
# roc implies that both LR and svm correctly ranks a diabetic higher than a non
# diabetic 82% of the time
# slides the threshold from 0-1,compile step,plots the curve

(np.float64(0.8242424242424242), np.float64(0.8249770431588613))